# -*- coding: utf-8 -*-
"""Crawl_Trangbao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/107m5yCv4h0xDUWvf4irK50WZH0IuGnRr
"""

!apt update
!apt install chromium-chromedriver
!pip install selenium

from selenium import webdriver
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
import csv
import pandas as pd
import os

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

"""#  Trang bao"""

driver = webdriver.Chrome(options=options)
url = 'https://vnexpress.net/'
driver.get(url)
soup = BeautifulSoup(driver.page_source)
print(soup.prettify)

category = soup.find_all('a', {'class':'count_cmt'})

list_url_category = []
for link in category:
  list_url_category.append(link.get("href"))
for i in list_url_category:
  print(i)
#link = list_url_category[1]
#list_url_category.pop(1)

df = pd.DataFrame()
title = []
href = []
time = []
comment = []
for i in list_url_category:
    driver.get(i)
    soup = BeautifulSoup(driver.page_source)
    #print(soup.prettify())
    x = soup.find('span',{"class":"date"})
    if (x==None):
      x = soup.find('span',{"class":"time"})
    y = soup.find('h1',{'class':'title-detail'})
    if (y==None):
      y = soup.find('h1',{'class':'title'})

    if (y!=None and x!=None):
      time.append(x.get_text())
      title.append(y.get_text())
      href.append(i)
      cmt = soup.find('p',{"class":"recent-com"})
      if (cmt!=None):
        comment.append(cmt.get_text())
      else:
        cmt = soup.find('p',{"class":"full_content"})
        if (cmt != None):
          comment.append(cmt.get_text())
        else:
          comment.append('Khong co comment')

df['headline'] = title
df['article_link'] = href
df['date'] = time
df['special comment'] = comment
df